stages:
  - maven
  - docker
  - register
  - deploy

variables:
  QUERY_SUBDIR: "booking_service_query"
  COMMAND_SUBDIR: "booking_service_command"
  # Name of the common-module as stated in *-service/pom.xml.
  COMMON_SUBMODULE: "booking_service_common"
  # The maven-artifacts are all named "booking-service" without the appended "-refactored". Therefore the docker images follow this naming-scheme as well. Otherwise, $CI_PROJECT_NAME could be used.
  DOCKER_IMAGE_NAME_COMMAND: "booking-service-command"
  DOCKER_IMAGE_NAME_QUERY: "booking-service-query"
  DOCKER_IMAGE_REF_COMMAND: "$CI_REGISTRY/$DOCKER_IMAGE_PREFIX/$CI_PROJECT_NAME/$DOCKER_IMAGE_NAME_COMMAND:$CI_COMMIT_REF_SLUG"
  DOCKER_IMAGE_REF_QUERY: "$CI_REGISTRY/$DOCKER_IMAGE_PREFIX/$CI_PROJECT_NAME/$DOCKER_IMAGE_NAME_QUERY:$CI_COMMIT_REF_SLUG"

# Run maven. Builds and registers common-library
maven:build_common:
  stage: maven
  image: maven:3.6-jdk-11-slim
  script:
    - mvn deploy -s ci_settings.xml -pl "$COMMON_SUBMODULE"
  only:
    - main

# Build the docker images.
docker:build_command:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f "./$COMMAND_SUBDIR/gitlab-ci.Dockerfile" --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -t $DOCKER_IMAGE_REF_COMMAND "./$COMMAND_SUBDIR"
  only:
    - main

docker:build_query:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f "./$QUERY_SUBDIR/gitlab-ci.Dockerfile" --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -t $DOCKER_IMAGE_REF_QUERY "./$QUERY_SUBDIR"
  only:
    - main

# Push the images to the SEELAB docker registry.
push_to_registry:
  stage: register
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker push $DOCKER_IMAGE_REF_COMMAND
    - docker push $DOCKER_IMAGE_REF_QUERY
  only:
    - main

# Trigger "puls-platform/build" to pull and redeploy the new image on the VM.
deploy_service:
  stage: deploy
  image: curlimages/curl:latest
  # The '>' folds the whole script into one line (see https://docs.gitlab.com/ee/ci/yaml/#multi-line-commands).
  script:
    - >
      curl -X POST
      -F "token=$TRIGGER_PULS_PLATFORM_TOKEN"
      -F "ref=$CI_COMMIT_REF_SLUG"
      -F "variables[CALLER_DOCKER_IMAGE_NAME]=$CI_REGISTRY/$DOCKER_IMAGE_PREFIX/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH"
      -F "variables[CALLER_PROJECT_NAME]=$DOCKER_IMAGENAME_COMMAND $DOCKER_IMAGENAME_QUERY"
      -F "variables[CALLER_BRANCH]=$CI_COMMIT_REF_NAME"
      $TRIGGER_PULS_PLATFORM_URL
  only:
    - main
